"""empty message

Revision ID: 07bc45288e1a
Revises: 1cbf1c0f4ea5
Create Date: 2019-05-17 20:06:28.961520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07bc45288e1a'
down_revision = '1cbf1c0f4ea5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'sgb_Instructor', ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sgb_Instructor', type_='unique')
    # ### end Alembic commands ###
