"""empty message

Revision ID: 1cbf1c0f4ea5
Revises: efc1fd68ac01
Create Date: 2019-05-17 20:02:09.729572

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1cbf1c0f4ea5'
down_revision = 'efc1fd68ac01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sgb_Instructor', sa.Column('user_id', sa.Integer(), nullable=True))
    op.drop_constraint('sgb_Instructor_ibfk_1', 'sgb_Instructor', type_='foreignkey')
    op.create_foreign_key(None, 'sgb_Instructor', 'users', ['user_id'], ['id'])
    op.drop_column('sgb_Instructor', 'instructor_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sgb_Instructor', sa.Column('instructor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sgb_Instructor', type_='foreignkey')
    op.create_foreign_key('sgb_Instructor_ibfk_1', 'sgb_Instructor', 'users', ['instructor_id'], ['id'])
    op.drop_column('sgb_Instructor', 'user_id')
    # ### end Alembic commands ###
