"""empty message

Revision ID: 25c56b4b267f
Revises: 3720baf116d8
Create Date: 2019-05-12 04:47:16.490656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25c56b4b267f'
down_revision = '3720baf116d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sgb_Course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_name', sa.String(length=150), nullable=True),
    sa.Column('course_description', sa.String(length=4000), nullable=True),
    sa.Column('course_schedule', sa.String(length=200), nullable=True),
    sa.Column('course_startdate', sa.Date(), nullable=True),
    sa.Column('course_enddate', sa.Date(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['sgb_Instructor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sgb_Course')
    # ### end Alembic commands ###
