"""empty message

Revision ID: 3fc8aed1402f
Revises: ba8566d5c70b
Create Date: 2019-05-19 10:29:50.535955

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fc8aed1402f'
down_revision = 'ba8566d5c70b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sgb_Course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.String(length=150), nullable=True),
    sa.Column('course_name', sa.String(length=150), nullable=True),
    sa.Column('course_description', sa.String(length=4000), nullable=True),
    sa.Column('course_schedule', sa.String(length=200), nullable=True),
    sa.Column('course_startdate', sa.DateTime(), nullable=True),
    sa.Column('course_enddate', sa.DateTime(), nullable=True),
    sa.Column('instructor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['instructor_id'], ['sgb_Instructor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sgb_Course')
    # ### end Alembic commands ###
