"""empty message

Revision ID: 4d65b34b1eeb
Revises: aca9623c3b60
Create Date: 2019-05-20 11:20:49.049527

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d65b34b1eeb'
down_revision = 'aca9623c3b60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sgb_StudentAssignment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('AssignmentName', sa.String(length=150), nullable=True),
    sa.Column('GradeTaken', sa.Integer(), nullable=True),
    sa.Column('GradeMax', sa.Integer(), nullable=True),
    sa.Column('student', sa.Integer(), nullable=True),
    sa.Column('course', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course'], ['sgb_Course.id'], ),
    sa.ForeignKeyConstraint(['student'], ['sgb_Student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sgb_StudentAssignment')
    # ### end Alembic commands ###
