"""empty message

Revision ID: 6bf73bd55e6f
Revises: 9bc9d3c8f567
Create Date: 2019-05-17 21:11:06.165868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bf73bd55e6f'
down_revision = '9bc9d3c8f567'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sgb_Course', sa.Column('instructor_Id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sgb_Course', 'sgb_Instructor', ['instructor_Id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sgb_Course', type_='foreignkey')
    op.drop_column('sgb_Course', 'instructor_Id')
    # ### end Alembic commands ###
