"""empty message

Revision ID: 9bc9d3c8f567
Revises: 07bc45288e1a
Create Date: 2019-05-17 20:25:08.323549

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9bc9d3c8f567'
down_revision = '07bc45288e1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('sgb_Course_ibfk_1', 'sgb_Course', type_='foreignkey')
    op.drop_column('sgb_Course', 'instructor_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sgb_Course', sa.Column('instructor_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('sgb_Course_ibfk_1', 'sgb_Course', 'sgb_Instructor', ['instructor_id'], ['id'])
    # ### end Alembic commands ###
