"""empty message

Revision ID: ba8566d5c70b
Revises: 6bf73bd55e6f
Create Date: 2019-05-19 10:27:54.002791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba8566d5c70b'
down_revision = '6bf73bd55e6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sgb_Course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.String(length=150), nullable=True),
    sa.Column('course_name', sa.String(length=150), nullable=True),
    sa.Column('course_description', sa.String(length=4000), nullable=True),
    sa.Column('course_schedule', sa.String(length=200), nullable=True),
    sa.Column('course_startdate', sa.DateTime(), nullable=True),
    sa.Column('course_enddate', sa.DateTime(), nullable=True),
    sa.Column('instructor_Id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['instructor_Id'], ['sgb_Instructor.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sgb_Course')
    # ### end Alembic commands ###
