"""empty message

Revision ID: deff77f9e625
Revises: fd82d9dc6507
Create Date: 2019-05-21 02:27:58.806481

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'deff77f9e625'
down_revision = 'fd82d9dc6507'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sgb_StudentAssignment', 'AssignmentName')
    op.drop_column('sgb_StudentAssignment', 'GradeMax')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sgb_StudentAssignment', sa.Column('GradeMax', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('sgb_StudentAssignment', sa.Column('AssignmentName', mysql.VARCHAR(length=150), nullable=True))
    # ### end Alembic commands ###
