"""empty message

Revision ID: efc1fd68ac01
Revises: 25c56b4b267f
Create Date: 2019-05-16 02:20:53.494233

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efc1fd68ac01'
down_revision = '25c56b4b267f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sgb_Course', sa.Column('instructor_id', sa.Integer(), nullable=True))
    op.drop_constraint('sgb_Course_ibfk_1', 'sgb_Course', type_='foreignkey')
    op.create_foreign_key(None, 'sgb_Course', 'sgb_Instructor', ['instructor_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sgb_Course', type_='foreignkey')
    op.create_foreign_key('sgb_Course_ibfk_1', 'sgb_Course', 'sgb_Instructor', ['course_id'], ['id'])
    op.drop_column('sgb_Course', 'instructor_id')
    # ### end Alembic commands ###
