"""empty message

Revision ID: fd82d9dc6507
Revises: 4d65b34b1eeb
Create Date: 2019-05-21 02:00:30.261538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd82d9dc6507'
down_revision = '4d65b34b1eeb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sgb_StudentAssignment', sa.Column('assignment', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'sgb_StudentAssignment', 'sgb_Assignment', ['assignment'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sgb_StudentAssignment', type_='foreignkey')
    op.drop_column('sgb_StudentAssignment', 'assignment')
    # ### end Alembic commands ###
